builds:
  -
    binary: gb-find-code-refs
    id: gb-find-code-refs
    main: ./cmd/gb-find-code-refs/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64

    ignore:
      - goos: darwin
        goarch: 386
  -
    binary: gb-find-code-refs-github-action
    id: gb-find-code-refs-github-action
    main: ./build/package/github-actions/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  -
    binary: gb-find-code-refs-bitbucket-pipeline
    id: gb-find-code-refs-bitbucket-pipeline
    main: ./build/package/bitbucket-pipelines/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  -
    id: gb-find-code-refs
    builds:
    - gb-find-code-refs

nfpms:
  -
    id: gb-find-code-refs
    file_name_template: >-
      {{- .ProjectName -}}_
      {{- .Version -}}.
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end -}}

    homepage: https://growthbook.com/
    maintainer: GrowthBook <support@growthbook.com>
    description: Job for finding feature flag code references
    license: Apache 2.0
    vendor: GrowthBook

    formats:
    - deb
    - rpm

brews:
  -
    ids:
    - gb-find-code-refs

    name: gb-find-code-refs

    description: Job for finding feature flag code references to GrowthBook

    homepage: "https://growthbook.com"

    repository:
      owner: growthbook
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    folder: Formula

    url_template: "https://github.com/growthbook/gb-find-code-refs/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    install: |
      bin.install "gb-find-code-refs"

    commit_author:
      name: GrowthBookReleaseBot
      email: growthbookreleasebot@growthbook.com

release:
  disable: true # this disables releasing *to GitHub*; it will still push to Docker
  # (we want Releaser to be responsible for doing all the GitHub release manipulations)

dockers:
  -
    image_templates:
    - "growthbook/gb-find-code-refs:latest"
    - "growthbook/gb-find-code-refs:{{ .Version }}"

    dockerfile: Dockerfile

  -
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    ids:
    - gb-find-code-refs-github-action

    image_templates:
    - "growthbook/gb-find-code-refs-github-action:latest"
    - "growthbook/gb-find-code-refs-github-action:{{ .Version }}"

    dockerfile: Dockerfile.github
  -
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    image_templates:
    - "growthbook/gb-find-code-refs-bitbucket-pipeline:latest"
    - "growthbook/gb-find-code-refs-bitbucket-pipeline:{{ .Version }}"

    ids:
    - gb-find-code-refs-bitbucket-pipeline

    dockerfile: Dockerfile.bitbucket
