FROM alpine:3.19.0

RUN apk update
RUN apk add --no-cache git

COPY gb-find-code-refs-github-action /gb-find-code-refs-github-action

LABEL com.github.actions.name="GrowthBook Code References"
LABEL com.github.actions.description="Find references to feature flags in your code."
LABEL com.github.actions.icon="toggle-right"
LABEL com.github.actions.color="gray-dark"
LABEL homepage="https://www.growthbook.com"

ENTRYPOINT ["/gb-find-code-refs-github-action"]
